# Usa a imagem base 'slim' para melhor compatibilidade com módulos nativos em Macs M1/M2/M3
FROM node:22-slim

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de dependência
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o resto do código-fonte
COPY . .

# Expõe a porta do Vite
EXPOSE 5173

# Comando padrão para iniciar o servidor de desenvolvimento
CMD ["npm", "run", "dev", "--", "--host"]