services:
  database:
    image: postgres:16-alpine
    container_name: linktree-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - backend-net

  backend:
    build:
      context: ./linktree-backend
      dockerfile: Dockerfile.dev
    container_name: linktree-backend
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./linktree-backend:/app
      - backend_node_modules:/app/node_modules
    networks:
      - frontend-net
      - backend-net

  frontend:
    build:
      context: ./linktree-app
      dockerfile: Dockerfile.dev
    container_name: linktree-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: http://localhost:3000
    volumes:
      - ./linktree-app:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - frontend-net

volumes:
  postgres-data:
  backend_node_modules:
  frontend_node_modules:

networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge