apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linktree-prod-postgresql
  namespace: prod
spec:
  instances: 3
  imageName: postgres:16-alpine
  
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "512MB"
      effective_cache_size: "2GB"
  
  bootstrap:
    initdb:
      database: linktree_prod
      owner: linktree_prod_user
      secret:
        name: linktree-prod-db-credentials
  
  storage:
    size: 20Gi
  
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "2000m"

---
apiVersion: v1
kind: Secret
metadata:
  name: linktree-prod-db-credentials
  namespace: prod
type: kubernetes.io/basic-auth
stringData:
  username: linktree_prod_user
  password: CHANGE-ME-STRONG-PASSWORD
