apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linktree-prod-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/periclesanfe/linktree-app.git
    targetRevision: HEAD
    path: argocd/apps/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
