apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linktree-dev-postgresql
  namespace: dev
spec:
  instances: 1
  imageName: postgres:16-alpine
  
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
  
  bootstrap:
    initdb:
      database: linktree_dev
      owner: linktree_dev_user
      secret:
        name: linktree-dev-db-credentials
  
  storage:
    size: 5Gi
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

---
apiVersion: v1
kind: Secret
metadata:
  name: linktree-dev-db-credentials
  namespace: dev
type: kubernetes.io/basic-auth
stringData:
  username: linktree_dev_user
  password: dev_password_123
