apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linktree-prod-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/periclesanfe/linktree-app.git
    targetRevision: HEAD
    path: helm/linktree
    helm:
      releaseName: linktree-prod
      valueFiles:
        - values.prod.yaml
      parameters:
        - name: backend.enabled
          value: "false"
        - name: frontend.enabled
          value: "true"

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
